//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService12.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validation", ReplyAction="http://tempuri.org/IService1/ValidationResponse")]
        string Validation(string url1, string url2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validation", ReplyAction="http://tempuri.org/IService1/ValidationResponse")]
        System.Threading.Tasks.Task<string> ValidationAsync(string url1, string url2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/html", ReplyAction="http://tempuri.org/IService1/htmlResponse")]
        string html(string url1, string url2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/html", ReplyAction="http://tempuri.org/IService1/htmlResponse")]
        System.Threading.Tasks.Task<string> htmlAsync(string url1, string url2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfService12.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfService12.ServiceReference1.IService1>, WcfService12.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Validation(string url1, string url2) {
            return base.Channel.Validation(url1, url2);
        }
        
        public System.Threading.Tasks.Task<string> ValidationAsync(string url1, string url2) {
            return base.Channel.ValidationAsync(url1, url2);
        }
        
        public string html(string url1, string url2) {
            return base.Channel.html(url1, url2);
        }
        
        public System.Threading.Tasks.Task<string> htmlAsync(string url1, string url2) {
            return base.Channel.htmlAsync(url1, url2);
        }
    }
}
